#!/usr/bin/env python3
"""Build eng/fixtures/archive from live archive (slim trees + re-exported sqlite).

Layout (same shape as production archive/):

    eng/fixtures/archive/
      research/<T>/<KEY>/   # slim session copy (no raw_sec/transcripts)
      catalog/research_compare.sqlite
      outcomes/…            # optional slim scorecards if present

Usage:
    python3 scripts/sync_eng_fixtures.py
    python3 scripts/sync_eng_fixtures.py --tickers META,JPM --dates 2026-08-03,2026-07-25
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SKIP_DIR_NAMES = frozenset({"raw_sec", "transcripts", "__pycache__", ".git"})

# Default slim set: prefer complete-looking sessions
DEFAULT_PAIRS = [
    ("META", "2026-08-03"),
    ("JPM", "2026-07-25"),
]


def _copy_session(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)

    def ignore(directory: str, names: list[str]) -> set[str]:
        skipped: set[str] = set()
        for n in names:
            p = Path(directory) / n
            if p.is_dir() and n in SKIP_DIR_NAMES:
                skipped.add(n)
        return skipped

    shutil.copytree(src, dst, ignore=ignore)


def _copy_outcomes_if_any(ticker: str, key: str, dest_archive: Path) -> None:
    src = PROJECT_ROOT / "archive" / "outcomes" / ticker / key
    if not src.is_dir():
        # try plain date prefix
        if "__" in key:
            src = PROJECT_ROOT / "archive" / "outcomes" / ticker / key.split("__", 1)[0]
    if not src.is_dir():
        return
    dst = dest_archive / "outcomes" / ticker / key
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def _export_fixture_sqlite(dest_project: Path, pairs: list[tuple[str, str]]) -> Path:
    """Export only fixture sessions into dest_project/archive/catalog/sqlite."""
    sys.path.insert(0, str(PROJECT_ROOT))
    from scripts.export_compare_db import export_session
    from scripts.kd_research.compare_db import count_runs, open_db

    conn = open_db(dest_project, rebuild=True)
    n_ok = 0
    for ticker, key in pairs:
        session = dest_project / "archive" / "research" / ticker / key
        if not session.is_dir():
            print(f"SKIP export missing {session}")
            continue
        # Never refresh snapshots on fixture trees in a way that touches live meta —
        # these are copies; refresh_snapshot=False keeps extract-only.
        try:
            export_session(session, conn, refresh_snapshot=False)
            n_ok += 1
        except Exception as e:  # noqa: BLE001
            print(f"WARN export {ticker} {key}: {e}")
    conn.commit()
    n = count_runs(conn)
    conn.close()
    db = dest_project / "archive" / "catalog" / "research_compare.sqlite"
    print(f"Fixture sqlite: exported {n_ok} session(s); DB runs={n} -> {db}")
    return db


def _write_fixture_indexes(dest_archive: Path, pairs: list[tuple[str, str]]) -> None:
    """Minimal runs_index so humans can browse fixtures without live rebuild."""
    from datetime import datetime, timezone

    runs = []
    for ticker, key in pairs:
        sess = dest_archive / "research" / ticker / key
        if not sess.is_dir():
            continue
        runs.append(
            {
                "run_id": f"research:{ticker}:{key}",
                "ticker": ticker,
                "session_date": key.split("__", 1)[0],
                "session_key": key,
                "path": f"archive/research/{ticker}/{key}",
                "is_production": "__" not in key,
            }
        )
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    cat = dest_archive / "catalog"
    cat.mkdir(parents=True, exist_ok=True)
    (cat / "runs_index.json").write_text(
        json.dumps({"schema_version": 2, "updated_at": now, "runs": runs}, indent=2)
        + "\n",
        encoding="utf-8",
    )
    (cat / "README.md").write_text(
        "Fixture catalog generated by scripts/sync_eng_fixtures.py.\n"
        "Query surface: research_compare.sqlite via packages.catalog_api "
        "with ARCHIVE_ROOT pointing at this archive/ directory.\n",
        encoding="utf-8",
    )


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tickers", help="Comma-separated (default: META,JPM)")
    ap.add_argument("--dates", help="Comma-separated session keys aligned with tickers")
    ap.add_argument(
        "--dest",
        type=Path,
        default=PROJECT_ROOT / "eng" / "fixtures",
        help="Fixture *project* root (contains archive/). Default: eng/fixtures",
    )
    args = ap.parse_args(argv)

    if args.tickers and args.dates:
        tickers = [t.strip().upper() for t in args.tickers.split(",") if t.strip()]
        dates = [d.strip() for d in args.dates.split(",") if d.strip()]
        if len(dates) == 1 and len(tickers) > 1:
            pairs = [(t, dates[0]) for t in tickers]
        elif len(tickers) == 1 and len(dates) > 1:
            pairs = [(tickers[0], d) for d in dates]
        elif len(tickers) == len(dates):
            pairs = list(zip(tickers, dates))
        else:
            print("ERROR: tickers/dates length mismatch", file=sys.stderr)
            return 1
    else:
        pairs = list(DEFAULT_PAIRS)

    dest_project: Path = args.dest
    dest_archive = dest_project / "archive"
    src_root = PROJECT_ROOT / "archive" / "research"

    copied: list[tuple[str, str]] = []
    for ticker, key in pairs:
        src = src_root / ticker / key
        if not src.is_dir():
            print(f"SKIP missing live session: {src}")
            continue
        dst = dest_archive / "research" / ticker / key
        print(f"Copy {src.relative_to(PROJECT_ROOT)} -> {dst.relative_to(PROJECT_ROOT)}")
        _copy_session(src, dst)
        _copy_outcomes_if_any(ticker, key, dest_archive)
        copied.append((ticker, key))

    if not copied:
        print("ERROR: no sessions copied", file=sys.stderr)
        return 1

    _export_fixture_sqlite(dest_project, copied)
    _write_fixture_indexes(dest_archive, copied)

    # Sanity: catalog_api against fixtures
    sys.path.insert(0, str(PROJECT_ROOT))
    from packages.catalog_api.client import CatalogApi

    api = CatalogApi(archive_root=dest_archive, readonly=True)
    h = api.health()
    print(f"Fixture health: db_exists={h.get('db_exists')} run_count={h.get('run_count')}")
    if not h.get("db_exists") or not h.get("run_count"):
        print("ERROR: fixture catalog empty", file=sys.stderr)
        return 2
    print(f"Done. ARCHIVE_ROOT for CI: {dest_archive}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
